apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-nfs-pv-claim
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-nfs-pv
  labels:
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/nfs3/mariadb_data
    server: 192.168.56.105 
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-internal-service
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec: # specification for deployment resource
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template: # blueprint for pods
    metadata:
      labels:
        app: mariadb # service will look for this label
    spec: # specification for pods
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306 #default one
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password
        - name: MARIADB_DATABASE
          value: wordpress
        volumeMounts:
        - name: mariadb-nfs-pv
          mountPath: /var/lib/mysql
      readinessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 150
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 120
        periodSeconds: 20
      volumes:
      - name: mariadb-nfs-pv
        persistentVolumeClaim:
          claimName: mariadb-nfs-pv-claim
